
<div class="docs-middle">
	<div class="container container-center">
		<div class="row" data-row-margin>
			<?php get_sidebar('core'); ?>
			<div class="docs-main col-9-12-medium">
				<article class="article" itemscope itemtype="http://schema.org/Article">
					<h1 class="article-title" itemprop="headline">Icon</h1>
					<p class="article-lead" itemprop="about">Place vector icons anywhere using an icon font.</p>

				<?php

					require_once __DIR__ . '/objects/usage.php';
					require_once __DIR__ . '/objects/icon-hover.php';
					require_once __DIR__ . '/objects/icon-button.php';

					require_once __DIR__ . '/modifiers/index.php';

					// require_once __DIR__ . '/objects/size-mod.php';

				?>

					<hr>
					<h2 id="icon-mapping"><a href="#icon-mapping" class="link-reset">List of all icons</a></h2>
					<p>Below is a list of all <code>.icon-*</code> classes provided by <a href="http://icomoon.io/" target="_blank">IcoMoon</a>.</p>
<?php
	$array = array(
		'Arrows' => array(
			'.icon-chevron-down',
			'.icon-chevron-left',
			'.icon-chevron-right',
			'.icon-chevron-up',
			'.icon-arrow-up-left',
			'.icon-arrow-up',
			'.icon-arrow-up-right',
			'.icon-arrow-right',
			'.icon-arrow-down-right',
			'.icon-arrow-down',
			'.icon-arrow-down-left',
			'.icon-arrow-left',
			'.icon-arrow-up-left2',
			'.icon-arrow-up2',
			'.icon-arrow-up-right2',
			'.icon-arrow-right2',
			'.icon-arrow-down-right2',
			'.icon-arrow-down2',
			'.icon-arrow-down-left2',
			'.icon-arrow-left2',
			'.icon-circle-up',
			'.icon-circle-right',
			'.icon-circle-down',
			'.icon-circle-left',
			'.icon-point-up',
			'.icon-point-right',
			'.icon-point-down',
			'.icon-point-left',
		),
		'Locations' => array(
			'.icon-home',
			'.icon-home2',
			'.icon-home3',
			'.icon-office',
			'.icon-library',
		),
		'Writing/Blogging' => array(
			'.icon-newspaper',
			'.icon-pencil',
			'.icon-pencil2',
			'.icon-quill',
			'.icon-pen',
			'.icon-blog',
		),
		'Images &amp; Image Editing' => array(
			'.icon-eyedropper',
			'.icon-droplet',
			'.icon-paint-format',
			'.icon-image',
			'.icon-images',
			'.icon-camera',
			'.icon-sun',
			'.icon-contrast',
			'.icon-brightness-contrast',
			'.icon-crop',
			'.icon-make-group',
			'.icon-ungroup',
			'.icon-scissors',
		),
		'Media' => array(
			'.icon-headphones',
			'.icon-music',
			'.icon-play',
			'.icon-film',
			'.icon-video-camera',
		),
		'Games' => array(
			'.icon-dice',
			'.icon-pacman',
			'.icon-spades',
			'.icon-clubs',
			'.icon-diamonds',
		),
		'Communication' => array(
			'.icon-bullhorn',
			'.icon-connection',
			'.icon-podcast',
			'.icon-feed',
			'.icon-mic',
			'.icon-book',
			'.icon-books',
			'.icon-phone',
			'.icon-phone-hang-up',
			'.icon-address-book',
			'.icon-envelop',
			'.icon-bubble',
			'.icon-bubbles',
			'.icon-bubbles2',
			'.icon-bubble2',
			'.icon-bubbles3',
			'.icon-bubbles4',
			'.icon-quotes-left',
			'.icon-quotes-right',
		),
		'File Types' => array(
			'.icon-file-text',
			'.icon-profile',
			'.icon-file-empty',
			'.icon-files-empty',
			'.icon-file-text2',
			'.icon-file-picture',
			'.icon-file-music',
			'.icon-file-play',
			'.icon-file-video',
			'.icon-file-zip',
			'.icon-file-pdf',
			'.icon-file-openoffice',
			'.icon-file-word',
			'.icon-file-excel',
		),
		'Text Editor' => array(
			'.icon-copy',
			'.icon-paste',
			'.icon-stack',
			'.icon-folder',
			'.icon-folder-open',
			'.icon-folder-plus',
			'.icon-folder-minus',
			'.icon-folder-download',
			'.icon-folder-upload',
			'.icon-undo',
			'.icon-redo',
			'.icon-undo2',
			'.icon-redo2',
			'.icon-forward',
			'.icon-reply',
			'.icon-search',
			'.icon-zoom-in',
			'.icon-zoom-out',
			'.icon-enlarge',
			'.icon-shrink',
			'.icon-enlarge2',
			'.icon-shrink2',
			'.icon-bin',
			'.icon-bin2',
			'.icon-clipboard',
			'.icon-list-numbered',
			'.icon-list',
			'.icon-list2',
			'.icon-link',
			'.icon-attachment',
			'.icon-font',
			'.icon-ligature',
			'.icon-ligature2',
			'.icon-text-height',
			'.icon-text-width',
			'.icon-font-size',
			'.icon-bold',
			'.icon-underline',
			'.icon-italic',
			'.icon-strikethrough',
			'.icon-page-break',
			'.icon-superscript',
			'.icon-subscript',
			'.icon-superscript2',
			'.icon-subscript2',
			'.icon-text-color',
			'.icon-pagebreak',
			'.icon-clear-formatting',
			'.icon-pilcrow',
			'.icon-ltr',
			'.icon-rtl',
			'.icon-section',
			'.icon-paragraph-left',
			'.icon-paragraph-center',
			'.icon-paragraph-right',
			'.icon-paragraph-justify',
			'.icon-indent-increase',
			'.icon-indent-decrease',
		),
		'Currency &amp; Commerce' => array(
			'.icon-price-tag',
			'.icon-price-tags',
			'.icon-barcode',
			'.icon-qrcode',
			'.icon-ticket',
			'.icon-cart',
			'.icon-coin-dollar',
			'.icon-coin-euro',
			'.icon-coin-pound',
			'.icon-coin-yen',
			'.icon-credit-card',
			'.icon-calculator',
		),
		'Map &amp; Location' => array(
			'.icon-pushpin',
			'.icon-location',
			'.icon-location2',
			'.icon-compass',
			'.icon-compass2',
			'.icon-map',
			'.icon-map2',
		),
		'Date &amp; Time' => array(
			'.icon-history',
			'.icon-clock',
			'.icon-clock2',
			'.icon-alarm',
			'.icon-bell',
			'.icon-stopwatch',
			'.icon-calendar',
			'.icon-hour-glass',
		),
		'Technology' => array(
			'.icon-printer',
			'.icon-keyboard',
			'.icon-display',
			'.icon-laptop',
			'.icon-mobile',
			'.icon-mobile2',
			'.icon-tablet',
			'.icon-tv',
			'.icon-drawer',
			'.icon-drawer2',
			'.icon-box-add',
			'.icon-box-remove',
			'.icon-download',
			'.icon-upload',
			'.icon-floppy-disk',
			'.icon-drive',
			'.icon-database',
			'.icon-cloud',
			'.icon-cloud-download',
			'.icon-cloud-upload',
			'.icon-cloud-check',
			'.icon-download2',
			'.icon-upload2',
			'.icon-download3',
			'.icon-upload3',
			'.icon-terminal',
			'.icon-embed',
			'.icon-embed2',
		),
		'People &amp; Users' => array(
			'.icon-user',
			'.icon-users',
			'.icon-user-plus',
			'.icon-user-minus',
			'.icon-user-check',
			'.icon-user-tie',
			'.icon-accessibility',
			'.icon-man',
			'.icon-woman',
			'.icon-man-woman',
		),
		'Loading' => array(
			'.icon-spinner',
			'.icon-spinner2',
			'.icon-spinner3',
			'.icon-spinner4',
			'.icon-spinner5',
			'.icon-spinner6',
			'.icon-spinner7',
			'.icon-spinner8',
			'.icon-spinner9',
			'.icon-spinner10',
			'.icon-spinner11',
		),
		'Charts' => array(
			'.icon-pie-chart',
			'.icon-stats-dots',
			'.icon-stats-bars',
			'.icon-stats-bars2',
			'.icon-meter',
			'.icon-meter2',
		),
		'Transportation' => array(
			'.icon-briefcase',
			'.icon-airplane',
			'.icon-truck',
			'.icon-road',
		),
		'User Interface' => array(
			'.icon-menu',
			'.icon-menu2',
			'.icon-menu3',
			'.icon-menu4',
			'.icon-eye',
			'.icon-eye-plus',
			'.icon-eye-minus',
			'.icon-eye-blocked',
			'.icon-bookmark',
			'.icon-bookmarks',
			'.icon-star-empty',
			'.icon-star-half',
			'.icon-star-full',
			'.icon-warning',
			'.icon-notification',
			'.icon-question',
			'.icon-plus',
			'.icon-minus',
			'.icon-info',
			'.icon-cancel-circle',
			'.icon-blocked',
			'.icon-cross',
			'.icon-checkmark',
			'.icon-checkmark2',
			'.icon-spell-check',
			'.icon-enter',
			'.icon-exit',
			'.icon-move-up',
			'.icon-move-down',
			'.icon-sort-alpha-asc',
			'.icon-sort-alpha-desc',
			'.icon-sort-numeric-asc',
			'.icon-sort-numberic-desc',
			'.icon-sort-amount-asc',
			'.icon-sort-amount-desc',
			'.icon-table',
			'.icon-table2',
			'.icon-insert-template',
			'.icon-share',
			'.icon-new-tab',
			'.icon-share2',
			'.icon-mail',
			'.icon-mail2',
			'.icon-mail3',
			'.icon-mail4',
		),
		'Emoticons' => array(
			'.icon-happy',
			'.icon-happy2',
			'.icon-smile',
			'.icon-smile2',
			'.icon-tongue',
			'.icon-tongue2',
			'.icon-sad',
			'.icon-sad2',
			'.icon-wink',
			'.icon-wink2',
			'.icon-grin',
			'.icon-grin2',
			'.icon-cool',
			'.icon-cool2',
			'.icon-angry',
			'.icon-angry2',
			'.icon-evil',
			'.icon-evil2',
			'.icon-shocked',
			'.icon-shocked2',
			'.icon-baffled',
			'.icon-baffled2',
			'.icon-confused',
			'.icon-confused2',
			'.icon-neutral',
			'.icon-neutral2',
			'.icon-hipster',
			'.icon-hipster2',
			'.icon-wondering',
			'.icon-wondering2',
			'.icon-sleepy',
			'.icon-sleepy2',
			'.icon-frustrated',
			'.icon-frustrated2',
			'.icon-crying',
			'.icon-crying2',
		),
		'Media Controls' => array(
			'.icon-play2',
			'.icon-pause',
			'.icon-stop',
			'.icon-previous',
			'.icon-next',
			'.icon-backward',
			'.icon-forward2',
			'.icon-play3',
			'.icon-pause2',
			'.icon-stop2',
			'.icon-backward2',
			'.icon-forward3',
			'.icon-first',
			'.icon-last',
			'.icon-previous2',
			'.icon-next2',
			'.icon-eject',
			'.icon-volume-high',
			'.icon-volume-medium',
			'.icon-volume-low',
			'.icon-volume-mute',
			'.icon-volume-mute2',
			'.icon-volume-increase',
			'.icon-volume-decrease',
			'.icon-loop',
			'.icon-loop2',
			'.icon-infinite',
			'.icon-shuffle',
		),
		'Keyboard Controls' => array(
			'.icon-tab',
			'.icon-command',
			'.icon-shift',
			'.icon-ctrl',
			'.icon-opt',
		),
		'Form Elements' => array(
			'.icon-checkbox-checked',
			'.icon-checkbox-unchecked',
			'.icon-radio-checked',
			'.icon-radio-checked2',
			'.icon-radio-unchecked',
		),
		'Math' => array(
			'.icon-filter',
			'.icon-omega',
			'.icon-sigma',
		),
		'Social Media &amp; Brand Icons' => array(
			'.icon-google',
			'.icon-google-plus',
			'.icon-google-plus2',
			'.icon-google-plus3',
			'.icon-google-drive',
			'.icon-facebook',
			'.icon-facebook2',
			'.icon-facebook3',
			'.icon-ello',
			'.icon-instagram',
			'.icon-twitter',
			'.icon-twitter2',
			'.icon-twitter3',
			'.icon-feed2',
			'.icon-feed3',
			'.icon-feed4',
			'.icon-youtube',
			'.icon-youtube2',
			'.icon-youtube3',
			'.icon-youtube4',
			'.icon-twitch',
			'.icon-vimeo',
			'.icon-vimeo2',
			'.icon-vimeo3',
			'.icon-lanyrd',
			'.icon-flickr',
			'.icon-flickr2',
			'.icon-flickr3',
			'.icon-flickr4',
			'.icon-picassa',
			'.icon-picassa2',
			'.icon-dribbble',
			'.icon-dribbble2',
			'.icon-dribbble3',
			'.icon-forrst',
			'.icon-forrst2',
			'.icon-deviantart',
			'.icon-deviantart2',
			'.icon-steam',
			'.icon-steam2',
			'.icon-dropbox',
			'.icon-onedrive',
			'.icon-github',
			'.icon-github2',
			'.icon-github3',
			'.icon-github4',
			'.icon-github5',
			'.icon-wordpress',
			'.icon-wordpress2',
			'.icon-joomla',
			'.icon-blogger',
			'.icon-blogger2',
			'.icon-tumblr',
			'.icon-tumblr2',
			'.icon-yahoo',
			'.icon-tux',
			'.icon-apple',
			'.icon-finder',
			'.icon-android',
			'.icon-windows',
			'.icon-windows8',
			'.icon-soundcloud',
			'.icon-soundcloud2',
			'.icon-skype',
			'.icon-reddit',
			'.icon-linkedin',
			'.icon-linkedin2',
			'.icon-lastfm',
			'.icon-lastfm2',
			'.icon-delicious',
			'.icon-stumbleupon',
			'.icon-stumbleupon2',
			'.icon-stackoverflow',
			'.icon-pinterest',
			'.icon-pinterest2',
			'.icon-xing',
			'.icon-xing2',
			'.icon-flattr',
			'.icon-foursquare',
			'.icon-paypal',
			'.icon-paypal2',
			'.icon-paypal3',
			'.icon-yelp',
			'.icon-libreoffice',
			'.icon-html5',
			'.icon-html52',
			'.icon-css3',
			'.icon-git',
			'.icon-svg',
			'.icon-codepen',
			'.icon-chrome',
			'.icon-firefox',
			'.icon-IE',
			'.icon-opera',
			'.icon-safari',
			'.icon-IcoMoon'
		),
		'Miscellaneous' => array(
			'.icon-lifebuoy',
			'.icon-binoculars',
			'.icon-key',
			'.icon-key2',
			'.icon-lock',
			'.icon-unlocked',
			'.icon-wrench',
			'.icon-equalizer',
			'.icon-equalizer2',
			'.icon-cog',
			'.icon-cogs',
			'.icon-hammer',
			'.icon-magic-wand',
			'.icon-aid-kit',
			'.icon-bug',
			'.icon-trophy',
			'.icon-gift',
			'.icon-glass',
			'.icon-glass2',
			'.icon-mug',
			'.icon-spoon-knife',
			'.icon-leaf',
			'.icon-rocket',
			'.icon-hammer2',
			'.icon-fire',
			'.icon-lab',
			'.icon-magnet',
			'.icon-target',
			'.icon-shield',
			'.icon-power',
			'.icon-switch',
			'.icon-power-cord',
			'.icon-sphere',
			'.icon-earth',
			'.icon-flag',
			'.icon-tree',
			'.icon-heart',
			'.icon-heart-broken',
		),
	);
	foreach($array as $title => $icons) {
		echo '<div class="row-margin docs-article-subtitle">';
			echo '<h3>' . $title . '</h3>';
		echo '</div>';
		echo '<div class="row row-margin row-3-cols">';
		foreach($icons as $icon) {
			echo '<div class="col margin-bottom docs-icon-col">';
				$class = 'icon ' . str_replace('.', '', $icon) . ' docs-icon';
				echo '<i class="' . $class . '"></i> <code>' . $icon . '</code>';
			echo '</div>';
		}
		echo '</div>';
	}
?>
					<?php get_microdata('author'); ?>
				</article>
			</div>
		</div>
	</div>
</div>
